Upgrade wheel cryptography to 1.5
Two versions are required: one compiled on centos, the other compiled
on debian.

There was problem on centos with the debian compiled version about versions
of libraries used:

ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

while centos use another name for the same library